apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: sample-app-deployment
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app-container
          image: shailesh349/sample-app:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster